version: "3.9"

services:
  nginx:
    image: nginx
    build: .
    ports:
      - "443:443"
    volumes:
      - ./nginx.conf:/home/erik/Desktop/Inception/srcs/requirements/nginx/nginx.conf
      - ./ssl:.etc